# .circleci/config.yml
version: 2
jobs:
  build:
    macos:
      xcode: "11.0.0"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      # A: Code checkout
      - checkout
      # B: Protobuf generation sequence
      - run:
          name: Install ProtoBuf
          # HOMEBREW_NO_AUTO_UPDATE=1
          # NOMEBREW_NO_INSTALL_CLEANUP=1
          command: brew install protobuf
      - run:
          name: Install Swift-ProtoBuf
          # HOMEBREW_NO_AUTO_UPDATE=1
          # NOMEBREW_NO_INSTALL_CLEANUP=1
          command: brew install swift-protobuf
      - run:
          name: Generate ProtoBuf Stubs
          command: ./gen-swift
      # C: iOS Code Signing Prep
      - run:
          name: Generate Certificate(s)
          # CIDEV_CERT=<secret>
          command: test "$CIDEV_CERT" && base64 --decode >'cidev.p12' <<< $CIDEV_CERT
      - run:
          name: Install Certificate(s)
          # CIDEV_PASSWD=<secret>
          command: fastlane gen_ci_cert
      - run:
          name: Generate Provisioning
          # CIDEV_PROV=<secret>
          command: test "$CIDEV_PROV" && base64 --decode >'cidev_prov.mobileprovision' <<< $CIDEV_PROV
      - run:
          name: Ensure Provisioning Directory
          command: mkdir -pv "~/Library/MobileDevice/Provisioning Profiles/"
      - run:
          name: Install Provisioning
          command: test "$CIDEV_PROV_UUID" && cp 'cidev_prov.mobileprovision' "~/Library/MobileDevice/Provisioning Profiles/$CIDEV_PROV_UUID.mobileprovision"
      # D: (ABC) Build
      - run:
          name: Build
          command: xcodebuild -workspace HGCApp.xcworkspace -scheme HGCApp_Debug
      # - run:
      #     name: Build and run tests
      #     command: fastlane scan
      #     environment:
      #       SCAN_DEVICE: iPhone 8
      #       SCAN_SCHEME: WebTests
      # - store_test_results:
      #     path: output/scan
      # - store_artifacts:
      #     path: output/pods

workflows:
  version: 2
  build:
    jobs:
      - build
